services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=${ORACLE_PWD}
    volumes:
      - oracle-xe-data:/opt/oracle/oradata
    networks:
      - backend
    restart: always

networks:
  backend:
volumes:
  oracle-xe-data:
